name: "CI"
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy, rustfmt

      - name: cargo fmt
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --all -- --check
      - name: cargo clippy
        uses: actions-rs/cargo@v1.0.3
        with:
          command: clippy
      - name: cargo test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
  ci-wasm32:
    name: CI-Wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          override: true
          target: wasm32-unknown-unknown

      - name: cargo check as wasm32
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --no-default-features --target wasm32-unknown-unknown
